/*
 * BatteryComms_public.h
 *
 *  Created on: 15 Mar 2021
 *      Author: Roberto
 */

#ifndef APPLICATIONS_BATTERY_COMMS_BATTERYCOMMS_PUBLIC_H_
#define APPLICATIONS_BATTERY_COMMS_BATTERYCOMMS_PUBLIC_H_





#endif /* APPLICATIONS_BATTERY_COMMS_BATTERYCOMMS_PUBLIC_H_ */
